# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkmDJpH2ZNKwDZgsk4A3GvHln4Z51pMr
"""

from google.colab.patches import cv2_imshow
import cv2
def mashinalar(markasi):
   if markasi== "chevrolet":
      rasm=cv2.imread("malibu.jpg")
      cv2_imshow(rasm)
      return "malibu"
   elif markasi== "audi":
      rasm=cv2.imread("q8.jpg")
      cv2_imshow(rasm)
      return "q8"
   elif markasi== "bmw":
      rasm=cv2.imread("x5.jpg")
      cv2_imshow(rasm)
      return "x5"
   elif markasi== "mercedes":
      rasm=cv2.imread("cla.jpg")
      cv2_imshow(rasm)
      return "cla"
   elif markasi== "toyota":
      rasm=cv2.imread("corolla.jpg")
      cv2_imshow(rasm)
      return "corolla"


markasi= input("mashina markasini kiriting")
natija=mashinalar(markasi)
print(natija)

"""# Новый раздел"""

from google.colab.patches import cv2_imshow
import cv2